import {
  Activity,
  Archive,
  Bell,
  Box,
  Boxes,
  Calendar,
  Clock,
  Cloud,
  Code,
  Compass,
  Cpu,
  Database,
  Download,
  File,
  FileText,
  Folder,
  Globe,
  HardDrive,
  Hash,
  Heart,
  HelpCircle,
  Home,
  Info,
  Layers,
  Library,
  Link,
  List,
  Lock,
  Map,
  MessageSquare,
  Monitor,
  Network,
  Package,
  Play,
  Plus,
  Puzzle,
  Radio,
  Search,
  Server,
  Settings,
  Shield,
  Sparkles,
  Star,
  Terminal,
  Upload,
  Users,
  Wrench,
  Zap,
} from 'lucide-react';

const ICONS = {
  activity: Activity,
  archive: Archive,
  bell: Bell,
  box: Box,
  boxes: Boxes,
  calendar: Calendar,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  compass: Compass,
  cpu: Cpu,
  database: Database,
  download: Download,
  file: File,
  'file-text': FileText,
  folder: Folder,
  globe: Globe,
  'hard-drive': HardDrive,
  hash: Hash,
  heart: Heart,
  'help-circle': HelpCircle,
  home: Home,
  info: Info,
  layers: Layers,
  library: Library,
  link: Link,
  list: List,
  lock: Lock,
  map: Map,
  'message-square': MessageSquare,
  monitor: Monitor,
  network: Network,
  package: Package,
  play: Play,
  plus: Plus,
  puzzle: Puzzle,
  radio: Radio,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  terminal: Terminal,
  upload: Upload,
  users: Users,
  wrench: Wrench,
  zap: Zap,
};

export function pluginIcon(name) {
  return ICONS[String(name || '').trim().toLowerCase()] || Puzzle;
}
